#pragma once

#include <iostream>
#include <istream>
#include <ostream>
#include <limits>
#include <memory>
#include <utility>
#include <algorithm>
#include <functional>
#include <optional>
#include <exception>
#include <type_traits>
#include <condition_variable>
#include <string>
#include <sstream>
#include <array>
#include <vector>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <initializer_list>
#include <fstream>
#include <filesystem>
#include <chrono>
#include <atomic>
#include <future>
#include <thread>
#include <mutex>
#include <cassert>
#include <cstdio>
#include <cstdint>
#include <cstddef>
#include <cstdlib>
#include <ctime>
#include <cmath>
#include <inttypes.h>

#ifdef VULTURE_PLATFORM_WINDOWS
#include <Windows.h>
#endif
